"""add finished and failed to taskstatus enum

Revision ID: 07b76d7b297b
Revises: fd4dc71b62ab
Create Date: 2026-01-13 17:32:52.464080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b76d7b297b'
down_revision: Union[str, Sequence[str], None] = 'fd4dc71b62ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
