"""Add unique constraint on task_id + status in TaskRun

Revision ID: 43a68ecdb4c8
Revises: abc123def456
Create Date: 2026-01-13 22:58:31.639763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a68ecdb4c8'
down_revision: Union[str, Sequence[str], None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_active_run', 'task_runs', ['task_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_active_run', 'task_runs', type_='unique')
    # ### end Alembic commands ###
