"""add task_runs table

Revision ID: 5b93c791f2d3
Revises: 0a33d4a4d21e
Create Date: 2026-01-13 15:05:52.672599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b93c791f2d3'
down_revision: Union[str, Sequence[str], None] = '0a33d4a4d21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    taskstatus_enum = postgresql.ENUM('active', 'paused', name='taskstatus', create_type=False)

    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', taskstatus_enum, nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_celery_task_id'), 'task_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_task_runs_id'), 'task_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_runs_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_celery_task_id'), table_name='task_runs')
    op.drop_table('task_runs')
    # ### end Alembic commands ###
