"""Add max run

Revision ID: afa787af8ca8
Revises: add_next_run_to_tasks
Create Date: 2026-01-14 21:19:21.037766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa787af8ca8'
down_revision: Union[str, Sequence[str], None] = 'add_next_run_to_tasks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_one_active_run_per_task'), table_name='task_runs', postgresql_where="(status = 'active'::taskstatus)")
    op.add_column('tasks', sa.Column('max_runs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_runs')
    op.create_index(op.f('uq_one_active_run_per_task'), 'task_runs', ['task_id'], unique=True, postgresql_where="(status = 'active'::taskstatus)")
    # ### end Alembic commands ###
