"""add user_id to task_runs

Revision ID: fd4dc71b62ab
Revises: 5b93c791f2d3
Create Date: 2026-01-13 16:38:45.062090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4dc71b62ab'
down_revision: Union[str, Sequence[str], None] = '5b93c791f2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_runs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_runs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_runs', type_='foreignkey')
    op.drop_column('task_runs', 'user_id')
    # ### end Alembic commands ###
